src/Entity/MotsCles.php
<?php

namespace App\Entity;

use App\Repository\MotsClesRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: MotsClesRepository::class)]
class MotsCles
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 25)]
    private $mot_cle;

    #[ORM\ManyToMany(targetEntity: Articles::class, inversedBy: 'motsCles')]
    private $articles;

    public function __construct()
    {
        $this->articles = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getMotCle(): ?string
    {
        return $this->mot_cle;
    }

    public function setMotCle(string $mot_cle): self
    {
        $this->mot_cle = $mot_cle;

        return $this;
    }

    /**
     * @return Collection<int, Articles>
     */
    public function getArticles(): Collection
    {
        return $this->articles;
    }

    public function addArticle(Articles $article): self
    {
        if (!$this->articles->contains($article)) {
            $this->articles[] = $article;
        }

        return $this;
    }

    public function removeArticle(Articles $article): self
    {
        $this->articles->removeElement($article);

        return $this;
    }
}

src/Form/MotsClesType.php
<?php

namespace App\Form;

use App\Entity\MotsCles;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class MotsClesType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('mot_cle')
            ->add('articles')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => MotsCles::class,
        ]);
    }
}

src/Controller/MotsClesController.php
<?php

namespace App\Controller;

use App\Entity\MotsCles;
use App\Form\MotsClesType;
use App\Repository\MotsClesRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/mots/cles')]
class MotsClesController extends AbstractController
{
    #[Route('/', name: 'app_mots_cles_index', methods: ['GET'])]
    public function index(MotsClesRepository $motsClesRepository): Response
    {
        return $this->render('mots_cles/index.html.twig', [
            'mots_cles' => $motsClesRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_mots_cles_new', methods: ['GET', 'POST'])]
    public function new(Request $request, MotsClesRepository $motsClesRepository): Response
    {
        $motsCle = new MotsCles();
        $form = $this->createForm(MotsClesType::class, $motsCle);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $motsClesRepository->add($motsCle, true);

            return $this->redirectToRoute('app_mots_cles_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('mots_cles/new.html.twig', [
            'mots_cle' => $motsCle,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_mots_cles_show', methods: ['GET'])]
    public function show(MotsCles $motsCle): Response
    {
        return $this->render('mots_cles/show.html.twig', [
            'mots_cle' => $motsCle,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_mots_cles_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, MotsCles $motsCle, MotsClesRepository $motsClesRepository): Response
    {
        $form = $this->createForm(MotsClesType::class, $motsCle);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $motsClesRepository->add($motsCle, true);

            return $this->redirectToRoute('app_mots_cles_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('mots_cles/edit.html.twig', [
            'mots_cle' => $motsCle,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_mots_cles_delete', methods: ['POST'])]
    public function delete(Request $request, MotsCles $motsCle, MotsClesRepository $motsClesRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$motsCle->getId(), $request->request->get('_token'))) {
            $motsClesRepository->remove($motsCle, true);
        }

        return $this->redirectToRoute('app_mots_cles_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/mots_cles/_delete_form.html.twig
<form method="post" action="{{ path('app_mots_cles_delete', {'id': mots_cle.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ mots_cle.id) }}">
    <button class="btn">Delete</button>
</form>

templates/mots_cles/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/mots_cles/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit MotsCles{% endblock %}

{% block body %}
    <h1>Edit MotsCles</h1>

    {{ include('mots_cles/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_mots_cles_index') }}">back to list</a>

    {{ include('mots_cles/_delete_form.html.twig') }}
{% endblock %}

templates/mots_cles/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}MotsCles index{% endblock %}

{% block body %}
    <h1>MotsCles index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Mot_cle</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for mots_cle in mots_cles %}
            <tr>
                <td>{{ mots_cle.id }}</td>
                <td>{{ mots_cle.motCle }}</td>
                <td>
                    <a href="{{ path('app_mots_cles_show', {'id': mots_cle.id}) }}">show</a>
                    <a href="{{ path('app_mots_cles_edit', {'id': mots_cle.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="3">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_mots_cles_new') }}">Create new</a>
{% endblock %}

templates/mots_cles/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New MotsCles{% endblock %}

{% block body %}
    <h1>Create new MotsCles</h1>

    {{ include('mots_cles/_form.html.twig') }}

    <a href="{{ path('app_mots_cles_index') }}">back to list</a>
{% endblock %}

templates/mots_cles/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}MotsCles{% endblock %}

{% block body %}
    <h1>MotsCles</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ mots_cle.id }}</td>
            </tr>
            <tr>
                <th>Mot_cle</th>
                <td>{{ mots_cle.motCle }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_mots_cles_index') }}">back to list</a>

    <a href="{{ path('app_mots_cles_edit', {'id': mots_cle.id}) }}">edit</a>

    {{ include('mots_cles/_delete_form.html.twig') }}
{% endblock %}